// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/radar.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -734747430;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_radar_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<Float32List> crateApiRadarLevel2Cuts({
    required List<int> data,
    required String moment,
  });

  Future<RadarFrame> crateApiRadarRenderLevel2Frame({
    required List<int> data,
    required String moment,
    required int elevationIndex,
    required int imageSize,
  });

  Future<RadarFrame> crateApiRadarRenderLevel3Frame({
    required List<int> data,
    required int imageSize,
  });

  Future<SampleResult> crateApiRadarSampleLevel2({
    required List<int> data,
    required String moment,
    required int elevationIndex,
    required double lat,
    required double lon,
  });

  Future<SampleResult> crateApiRadarSampleLevel3({
    required List<int> data,
    required double lat,
    required double lon,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<Float32List> crateApiRadarLevel2Cuts({
    required List<int> data,
    required String moment,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(moment, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarLevel2CutsConstMeta,
        argValues: [data, moment],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarLevel2CutsConstMeta => const TaskConstMeta(
    debugName: "level2_cuts",
    argNames: ["data", "moment"],
  );

  @override
  Future<RadarFrame> crateApiRadarRenderLevel2Frame({
    required List<int> data,
    required String moment,
    required int elevationIndex,
    required int imageSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(moment, serializer);
          sse_encode_u_32(elevationIndex, serializer);
          sse_encode_u_32(imageSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_radar_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarRenderLevel2FrameConstMeta,
        argValues: [data, moment, elevationIndex, imageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarRenderLevel2FrameConstMeta =>
      const TaskConstMeta(
        debugName: "render_level2_frame",
        argNames: ["data", "moment", "elevationIndex", "imageSize"],
      );

  @override
  Future<RadarFrame> crateApiRadarRenderLevel3Frame({
    required List<int> data,
    required int imageSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_u_32(imageSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_radar_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarRenderLevel3FrameConstMeta,
        argValues: [data, imageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarRenderLevel3FrameConstMeta =>
      const TaskConstMeta(
        debugName: "render_level3_frame",
        argNames: ["data", "imageSize"],
      );

  @override
  Future<SampleResult> crateApiRadarSampleLevel2({
    required List<int> data,
    required String moment,
    required int elevationIndex,
    required double lat,
    required double lon,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(moment, serializer);
          sse_encode_u_32(elevationIndex, serializer);
          sse_encode_f_64(lat, serializer);
          sse_encode_f_64(lon, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sample_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarSampleLevel2ConstMeta,
        argValues: [data, moment, elevationIndex, lat, lon],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarSampleLevel2ConstMeta => const TaskConstMeta(
    debugName: "sample_level2",
    argNames: ["data", "moment", "elevationIndex", "lat", "lon"],
  );

  @override
  Future<SampleResult> crateApiRadarSampleLevel3({
    required List<int> data,
    required double lat,
    required double lon,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_f_64(lat, serializer);
          sse_encode_f_64(lon, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sample_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarSampleLevel3ConstMeta,
        argValues: [data, lat, lon],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarSampleLevel3ConstMeta => const TaskConstMeta(
    debugName: "sample_level3",
    argNames: ["data", "lat", "lon"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  RadarFrame dco_decode_radar_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return RadarFrame(
      productCode: dco_decode_i_32(arr[0]),
      productName: dco_decode_String(arr[1]),
      unit: dco_decode_String(arr[2]),
      siteLat: dco_decode_f_64(arr[3]),
      siteLon: dco_decode_f_64(arr[4]),
      timestamp: dco_decode_i_64(arr[5]),
      elevationDeg: dco_decode_f_32(arr[6]),
      vcp: dco_decode_i_32(arr[7]),
      width: dco_decode_u_32(arr[8]),
      height: dco_decode_u_32(arr[9]),
      png: dco_decode_list_prim_u_8_strict(arr[10]),
      north: dco_decode_f_64(arr[11]),
      south: dco_decode_f_64(arr[12]),
      east: dco_decode_f_64(arr[13]),
      west: dco_decode_f_64(arr[14]),
    );
  }

  @protected
  SampleResult dco_decode_sample_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SampleResult(
      value: dco_decode_opt_box_autoadd_f_32(arr[0]),
      rangeFolded: dco_decode_bool(arr[1]),
      unit: dco_decode_String(arr[2]),
      distanceKm: dco_decode_f_64(arr[3]),
      beamHeightM: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RadarFrame sse_decode_radar_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_productCode = sse_decode_i_32(deserializer);
    var var_productName = sse_decode_String(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_siteLat = sse_decode_f_64(deserializer);
    var var_siteLon = sse_decode_f_64(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_elevationDeg = sse_decode_f_32(deserializer);
    var var_vcp = sse_decode_i_32(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_png = sse_decode_list_prim_u_8_strict(deserializer);
    var var_north = sse_decode_f_64(deserializer);
    var var_south = sse_decode_f_64(deserializer);
    var var_east = sse_decode_f_64(deserializer);
    var var_west = sse_decode_f_64(deserializer);
    return RadarFrame(
      productCode: var_productCode,
      productName: var_productName,
      unit: var_unit,
      siteLat: var_siteLat,
      siteLon: var_siteLon,
      timestamp: var_timestamp,
      elevationDeg: var_elevationDeg,
      vcp: var_vcp,
      width: var_width,
      height: var_height,
      png: var_png,
      north: var_north,
      south: var_south,
      east: var_east,
      west: var_west,
    );
  }

  @protected
  SampleResult sse_decode_sample_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_rangeFolded = sse_decode_bool(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_distanceKm = sse_decode_f_64(deserializer);
    var var_beamHeightM = sse_decode_f_64(deserializer);
    return SampleResult(
      value: var_value,
      rangeFolded: var_rangeFolded,
      unit: var_unit,
      distanceKm: var_distanceKm,
      beamHeightM: var_beamHeightM,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_radar_frame(RadarFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.productCode, serializer);
    sse_encode_String(self.productName, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_f_64(self.siteLat, serializer);
    sse_encode_f_64(self.siteLon, serializer);
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_f_32(self.elevationDeg, serializer);
    sse_encode_i_32(self.vcp, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.png, serializer);
    sse_encode_f_64(self.north, serializer);
    sse_encode_f_64(self.south, serializer);
    sse_encode_f_64(self.east, serializer);
    sse_encode_f_64(self.west, serializer);
  }

  @protected
  void sse_encode_sample_result(SampleResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_f_32(self.value, serializer);
    sse_encode_bool(self.rangeFolded, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_f_64(self.distanceKm, serializer);
    sse_encode_f_64(self.beamHeightM, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
