// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/radar.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1495060699;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_radar_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ColorScale> crateApiRadarColorScale({
    required int productCode,
    required String moment,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiRadarInspectOpenLevel2({
    required List<int> data,
    required String moment,
    required int elevationIndex,
  });

  Future<void> crateApiRadarInspectOpenLevel3({required List<int> data});

  Future<SampleResult> crateApiRadarInspectSample({
    required double lat,
    required double lon,
  });

  Future<Float64List> crateApiRadarInspectSite();

  Future<String> crateApiRadarInstallPalette({required String text});

  Future<Float32List> crateApiRadarLevel2Cuts({
    required List<int> data,
    required String moment,
  });

  Future<RadarFrame> crateApiRadarNowcastView({
    required List<int> prev,
    required List<int> latest,
    required String source,
    required double minutes,
    required double north,
    required double south,
    required double east,
    required double west,
    required int width,
    required int height,
  });

  Future<GlmResult> crateApiRadarParseGlm({required List<int> data});

  Future<RadarFrame> crateApiRadarRenderLevel2Frame({
    required List<int> data,
    required String moment,
    required int elevationIndex,
    required int imageSize,
  });

  Future<RadarFrame> crateApiRadarRenderLevel2View({
    required List<int> data,
    required String moment,
    required int elevationIndex,
    required double north,
    required double south,
    required double east,
    required double west,
    required int width,
    required int height,
  });

  Future<RadarFrame> crateApiRadarRenderLevel3Frame({
    required List<int> data,
    required int imageSize,
  });

  Future<RadarFrame> crateApiRadarRenderLevel3View({
    required List<int> data,
    required double north,
    required double south,
    required double east,
    required double west,
    required int width,
    required int height,
  });

  Future<RadarFrame> crateApiRadarRenderMrmsView({
    required List<int> data,
    required double north,
    required double south,
    required double east,
    required double west,
    required int width,
    required int height,
  });

  Future<Volume3DFrame> crateApiRadarRenderVolume3D({
    required List<int> data,
    required double yawDeg,
    required double pitchDeg,
    required double zoom,
    required double dbzMin,
    required int width,
    required int height,
  });

  Future<void> crateApiRadarResetPalettes();

  Future<SampleResult> crateApiRadarSampleLevel2({
    required List<int> data,
    required String moment,
    required int elevationIndex,
    required double lat,
    required double lon,
  });

  Future<SampleResult> crateApiRadarSampleLevel3({
    required List<int> data,
    required double lat,
    required double lon,
  });

  Future<List<StormTrack>> crateApiRadarStormTracks({required List<int> data});

  Future<Float64List> crateApiRadarVolume3DGroundBounds();

  Future<Volume3DInfo> crateApiRadarVolume3DOpen({
    required List<int> data,
    required String moment,
    required double threshold,
  });

  Future<RawFrame> crateApiRadarVolume3DRenderFly({
    required double eyeX,
    required double eyeY,
    required double eyeZ,
    required double yawDeg,
    required double pitchDeg,
    required List<double> clip,
    required int width,
    required int height,
  });

  Future<void> crateApiRadarVolume3DSetGround({
    required List<int> rgba,
    required int width,
    required int height,
  });

  Future<void> crateApiRadarVolume3DSetTerrain({
    required List<double> heights,
    required int width,
    required int height,
  });

  Future<void> crateApiRadarVolume3DSetThreshold({required double threshold});

  Future<void> crateApiRadarVolume3DShowCone({required bool show_});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ColorScale> crateApiRadarColorScale({
    required int productCode,
    required String moment,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(productCode, serializer);
          sse_encode_String(moment, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_color_scale,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarColorScaleConstMeta,
        argValues: [productCode, moment],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarColorScaleConstMeta => const TaskConstMeta(
    debugName: "color_scale",
    argNames: ["productCode", "moment"],
  );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiRadarInspectOpenLevel2({
    required List<int> data,
    required String moment,
    required int elevationIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(moment, serializer);
          sse_encode_u_32(elevationIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarInspectOpenLevel2ConstMeta,
        argValues: [data, moment, elevationIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarInspectOpenLevel2ConstMeta =>
      const TaskConstMeta(
        debugName: "inspect_open_level2",
        argNames: ["data", "moment", "elevationIndex"],
      );

  @override
  Future<void> crateApiRadarInspectOpenLevel3({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarInspectOpenLevel3ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarInspectOpenLevel3ConstMeta =>
      const TaskConstMeta(debugName: "inspect_open_level3", argNames: ["data"]);

  @override
  Future<SampleResult> crateApiRadarInspectSample({
    required double lat,
    required double lon,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(lat, serializer);
          sse_encode_f_64(lon, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sample_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarInspectSampleConstMeta,
        argValues: [lat, lon],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarInspectSampleConstMeta => const TaskConstMeta(
    debugName: "inspect_sample",
    argNames: ["lat", "lon"],
  );

  @override
  Future<Float64List> crateApiRadarInspectSite() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarInspectSiteConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarInspectSiteConstMeta =>
      const TaskConstMeta(debugName: "inspect_site", argNames: []);

  @override
  Future<String> crateApiRadarInstallPalette({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarInstallPaletteConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarInstallPaletteConstMeta =>
      const TaskConstMeta(debugName: "install_palette", argNames: ["text"]);

  @override
  Future<Float32List> crateApiRadarLevel2Cuts({
    required List<int> data,
    required String moment,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(moment, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarLevel2CutsConstMeta,
        argValues: [data, moment],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarLevel2CutsConstMeta => const TaskConstMeta(
    debugName: "level2_cuts",
    argNames: ["data", "moment"],
  );

  @override
  Future<RadarFrame> crateApiRadarNowcastView({
    required List<int> prev,
    required List<int> latest,
    required String source,
    required double minutes,
    required double north,
    required double south,
    required double east,
    required double west,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(prev, serializer);
          sse_encode_list_prim_u_8_loose(latest, serializer);
          sse_encode_String(source, serializer);
          sse_encode_f_32(minutes, serializer);
          sse_encode_f_64(north, serializer);
          sse_encode_f_64(south, serializer);
          sse_encode_f_64(east, serializer);
          sse_encode_f_64(west, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_radar_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarNowcastViewConstMeta,
        argValues: [
          prev,
          latest,
          source,
          minutes,
          north,
          south,
          east,
          west,
          width,
          height,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarNowcastViewConstMeta => const TaskConstMeta(
    debugName: "nowcast_view",
    argNames: [
      "prev",
      "latest",
      "source",
      "minutes",
      "north",
      "south",
      "east",
      "west",
      "width",
      "height",
    ],
  );

  @override
  Future<GlmResult> crateApiRadarParseGlm({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_glm_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarParseGlmConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarParseGlmConstMeta =>
      const TaskConstMeta(debugName: "parse_glm", argNames: ["data"]);

  @override
  Future<RadarFrame> crateApiRadarRenderLevel2Frame({
    required List<int> data,
    required String moment,
    required int elevationIndex,
    required int imageSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(moment, serializer);
          sse_encode_u_32(elevationIndex, serializer);
          sse_encode_u_32(imageSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_radar_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarRenderLevel2FrameConstMeta,
        argValues: [data, moment, elevationIndex, imageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarRenderLevel2FrameConstMeta =>
      const TaskConstMeta(
        debugName: "render_level2_frame",
        argNames: ["data", "moment", "elevationIndex", "imageSize"],
      );

  @override
  Future<RadarFrame> crateApiRadarRenderLevel2View({
    required List<int> data,
    required String moment,
    required int elevationIndex,
    required double north,
    required double south,
    required double east,
    required double west,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(moment, serializer);
          sse_encode_u_32(elevationIndex, serializer);
          sse_encode_f_64(north, serializer);
          sse_encode_f_64(south, serializer);
          sse_encode_f_64(east, serializer);
          sse_encode_f_64(west, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_radar_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarRenderLevel2ViewConstMeta,
        argValues: [
          data,
          moment,
          elevationIndex,
          north,
          south,
          east,
          west,
          width,
          height,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarRenderLevel2ViewConstMeta =>
      const TaskConstMeta(
        debugName: "render_level2_view",
        argNames: [
          "data",
          "moment",
          "elevationIndex",
          "north",
          "south",
          "east",
          "west",
          "width",
          "height",
        ],
      );

  @override
  Future<RadarFrame> crateApiRadarRenderLevel3Frame({
    required List<int> data,
    required int imageSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_u_32(imageSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_radar_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarRenderLevel3FrameConstMeta,
        argValues: [data, imageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarRenderLevel3FrameConstMeta =>
      const TaskConstMeta(
        debugName: "render_level3_frame",
        argNames: ["data", "imageSize"],
      );

  @override
  Future<RadarFrame> crateApiRadarRenderLevel3View({
    required List<int> data,
    required double north,
    required double south,
    required double east,
    required double west,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_f_64(north, serializer);
          sse_encode_f_64(south, serializer);
          sse_encode_f_64(east, serializer);
          sse_encode_f_64(west, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_radar_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarRenderLevel3ViewConstMeta,
        argValues: [data, north, south, east, west, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarRenderLevel3ViewConstMeta =>
      const TaskConstMeta(
        debugName: "render_level3_view",
        argNames: ["data", "north", "south", "east", "west", "width", "height"],
      );

  @override
  Future<RadarFrame> crateApiRadarRenderMrmsView({
    required List<int> data,
    required double north,
    required double south,
    required double east,
    required double west,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_f_64(north, serializer);
          sse_encode_f_64(south, serializer);
          sse_encode_f_64(east, serializer);
          sse_encode_f_64(west, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_radar_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarRenderMrmsViewConstMeta,
        argValues: [data, north, south, east, west, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarRenderMrmsViewConstMeta =>
      const TaskConstMeta(
        debugName: "render_mrms_view",
        argNames: ["data", "north", "south", "east", "west", "width", "height"],
      );

  @override
  Future<Volume3DFrame> crateApiRadarRenderVolume3D({
    required List<int> data,
    required double yawDeg,
    required double pitchDeg,
    required double zoom,
    required double dbzMin,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_f_32(yawDeg, serializer);
          sse_encode_f_32(pitchDeg, serializer);
          sse_encode_f_32(zoom, serializer);
          sse_encode_f_32(dbzMin, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_volume_3_d_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarRenderVolume3DConstMeta,
        argValues: [data, yawDeg, pitchDeg, zoom, dbzMin, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarRenderVolume3DConstMeta =>
      const TaskConstMeta(
        debugName: "render_volume3d",
        argNames: [
          "data",
          "yawDeg",
          "pitchDeg",
          "zoom",
          "dbzMin",
          "width",
          "height",
        ],
      );

  @override
  Future<void> crateApiRadarResetPalettes() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRadarResetPalettesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarResetPalettesConstMeta =>
      const TaskConstMeta(debugName: "reset_palettes", argNames: []);

  @override
  Future<SampleResult> crateApiRadarSampleLevel2({
    required List<int> data,
    required String moment,
    required int elevationIndex,
    required double lat,
    required double lon,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(moment, serializer);
          sse_encode_u_32(elevationIndex, serializer);
          sse_encode_f_64(lat, serializer);
          sse_encode_f_64(lon, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sample_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarSampleLevel2ConstMeta,
        argValues: [data, moment, elevationIndex, lat, lon],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarSampleLevel2ConstMeta => const TaskConstMeta(
    debugName: "sample_level2",
    argNames: ["data", "moment", "elevationIndex", "lat", "lon"],
  );

  @override
  Future<SampleResult> crateApiRadarSampleLevel3({
    required List<int> data,
    required double lat,
    required double lon,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_f_64(lat, serializer);
          sse_encode_f_64(lon, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sample_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarSampleLevel3ConstMeta,
        argValues: [data, lat, lon],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarSampleLevel3ConstMeta => const TaskConstMeta(
    debugName: "sample_level3",
    argNames: ["data", "lat", "lon"],
  );

  @override
  Future<List<StormTrack>> crateApiRadarStormTracks({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_storm_track,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarStormTracksConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarStormTracksConstMeta =>
      const TaskConstMeta(debugName: "storm_tracks", argNames: ["data"]);

  @override
  Future<Float64List> crateApiRadarVolume3DGroundBounds() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarVolume3DGroundBoundsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarVolume3DGroundBoundsConstMeta =>
      const TaskConstMeta(debugName: "volume3d_ground_bounds", argNames: []);

  @override
  Future<Volume3DInfo> crateApiRadarVolume3DOpen({
    required List<int> data,
    required String moment,
    required double threshold,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(moment, serializer);
          sse_encode_f_32(threshold, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_volume_3_d_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarVolume3DOpenConstMeta,
        argValues: [data, moment, threshold],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarVolume3DOpenConstMeta => const TaskConstMeta(
    debugName: "volume3d_open",
    argNames: ["data", "moment", "threshold"],
  );

  @override
  Future<RawFrame> crateApiRadarVolume3DRenderFly({
    required double eyeX,
    required double eyeY,
    required double eyeZ,
    required double yawDeg,
    required double pitchDeg,
    required List<double> clip,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(eyeX, serializer);
          sse_encode_f_32(eyeY, serializer);
          sse_encode_f_32(eyeZ, serializer);
          sse_encode_f_32(yawDeg, serializer);
          sse_encode_f_32(pitchDeg, serializer);
          sse_encode_list_prim_f_32_loose(clip, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_raw_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarVolume3DRenderFlyConstMeta,
        argValues: [eyeX, eyeY, eyeZ, yawDeg, pitchDeg, clip, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarVolume3DRenderFlyConstMeta =>
      const TaskConstMeta(
        debugName: "volume3d_render_fly",
        argNames: [
          "eyeX",
          "eyeY",
          "eyeZ",
          "yawDeg",
          "pitchDeg",
          "clip",
          "width",
          "height",
        ],
      );

  @override
  Future<void> crateApiRadarVolume3DSetGround({
    required List<int> rgba,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(rgba, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarVolume3DSetGroundConstMeta,
        argValues: [rgba, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarVolume3DSetGroundConstMeta =>
      const TaskConstMeta(
        debugName: "volume3d_set_ground",
        argNames: ["rgba", "width", "height"],
      );

  @override
  Future<void> crateApiRadarVolume3DSetTerrain({
    required List<double> heights,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(heights, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarVolume3DSetTerrainConstMeta,
        argValues: [heights, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarVolume3DSetTerrainConstMeta =>
      const TaskConstMeta(
        debugName: "volume3d_set_terrain",
        argNames: ["heights", "width", "height"],
      );

  @override
  Future<void> crateApiRadarVolume3DSetThreshold({required double threshold}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(threshold, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarVolume3DSetThresholdConstMeta,
        argValues: [threshold],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarVolume3DSetThresholdConstMeta =>
      const TaskConstMeta(
        debugName: "volume3d_set_threshold",
        argNames: ["threshold"],
      );

  @override
  Future<void> crateApiRadarVolume3DShowCone({required bool show_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(show_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRadarVolume3DShowConeConstMeta,
        argValues: [show_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRadarVolume3DShowConeConstMeta =>
      const TaskConstMeta(debugName: "volume3d_show_cone", argNames: ["show_"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  ColorScale dco_decode_color_scale(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ColorScale(
      stops: dco_decode_list_color_scale_stop(arr[0]),
      interpolate: dco_decode_bool(arr[1]),
      unit: dco_decode_String(arr[2]),
      rfR: dco_decode_u_8(arr[3]),
      rfG: dco_decode_u_8(arr[4]),
      rfB: dco_decode_u_8(arr[5]),
    );
  }

  @protected
  ColorScaleStop dco_decode_color_scale_stop(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ColorScaleStop(
      value: dco_decode_f_32(arr[0]),
      r: dco_decode_u_8(arr[1]),
      g: dco_decode_u_8(arr[2]),
      b: dco_decode_u_8(arr[3]),
      a: dco_decode_u_8(arr[4]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GlmResult dco_decode_glm_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GlmResult(
      timestamp: dco_decode_i_64(arr[0]),
      lats: dco_decode_list_prim_f_32_strict(arr[1]),
      lons: dco_decode_list_prim_f_32_strict(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<ColorScaleStop> dco_decode_list_color_scale_stop(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_color_scale_stop).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StormTrack> dco_decode_list_storm_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_storm_track).toList();
  }

  @protected
  List<TrackPoint> dco_decode_list_track_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track_point).toList();
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  RadarFrame dco_decode_radar_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return RadarFrame(
      productCode: dco_decode_i_32(arr[0]),
      productName: dco_decode_String(arr[1]),
      unit: dco_decode_String(arr[2]),
      siteLat: dco_decode_f_64(arr[3]),
      siteLon: dco_decode_f_64(arr[4]),
      timestamp: dco_decode_i_64(arr[5]),
      elevationDeg: dco_decode_f_32(arr[6]),
      vcp: dco_decode_i_32(arr[7]),
      width: dco_decode_u_32(arr[8]),
      height: dco_decode_u_32(arr[9]),
      png: dco_decode_list_prim_u_8_strict(arr[10]),
      north: dco_decode_f_64(arr[11]),
      south: dco_decode_f_64(arr[12]),
      east: dco_decode_f_64(arr[13]),
      west: dco_decode_f_64(arr[14]),
    );
  }

  @protected
  RawFrame dco_decode_raw_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RawFrame(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      rgba: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  SampleResult dco_decode_sample_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SampleResult(
      value: dco_decode_opt_box_autoadd_f_32(arr[0]),
      rangeFolded: dco_decode_bool(arr[1]),
      unit: dco_decode_String(arr[2]),
      distanceKm: dco_decode_f_64(arr[3]),
      beamHeightM: dco_decode_f_64(arr[4]),
      azimuthDeg: dco_decode_f_64(arr[5]),
      elevationDeg: dco_decode_f_32(arr[6]),
    );
  }

  @protected
  StormTrack dco_decode_storm_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return StormTrack(
      id: dco_decode_String(arr[0]),
      lat: dco_decode_f_64(arr[1]),
      lon: dco_decode_f_64(arr[2]),
      tracked: dco_decode_bool(arr[3]),
      speedKt: dco_decode_f_32(arr[4]),
      headingDeg: dco_decode_f_32(arr[5]),
      forecast: dco_decode_list_track_point(arr[6]),
      errorNm: dco_decode_f_32(arr[7]),
    );
  }

  @protected
  TrackPoint dco_decode_track_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TrackPoint(
      minutes: dco_decode_f_32(arr[0]),
      lat: dco_decode_f_64(arr[1]),
      lon: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  Volume3DFrame dco_decode_volume_3_d_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Volume3DFrame(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      png: dco_decode_list_prim_u_8_strict(arr[2]),
      timestamp: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  Volume3DInfo dco_decode_volume_3_d_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Volume3DInfo(
      gpu: dco_decode_bool(arr[0]),
      halfExtentM: dco_decode_f_32(arr[1]),
      topM: dco_decode_f_32(arr[2]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  ColorScale sse_decode_color_scale(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stops = sse_decode_list_color_scale_stop(deserializer);
    var var_interpolate = sse_decode_bool(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_rfR = sse_decode_u_8(deserializer);
    var var_rfG = sse_decode_u_8(deserializer);
    var var_rfB = sse_decode_u_8(deserializer);
    return ColorScale(
      stops: var_stops,
      interpolate: var_interpolate,
      unit: var_unit,
      rfR: var_rfR,
      rfG: var_rfG,
      rfB: var_rfB,
    );
  }

  @protected
  ColorScaleStop sse_decode_color_scale_stop(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_f_32(deserializer);
    var var_r = sse_decode_u_8(deserializer);
    var var_g = sse_decode_u_8(deserializer);
    var var_b = sse_decode_u_8(deserializer);
    var var_a = sse_decode_u_8(deserializer);
    return ColorScaleStop(
      value: var_value,
      r: var_r,
      g: var_g,
      b: var_b,
      a: var_a,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GlmResult sse_decode_glm_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_lats = sse_decode_list_prim_f_32_strict(deserializer);
    var var_lons = sse_decode_list_prim_f_32_strict(deserializer);
    return GlmResult(timestamp: var_timestamp, lats: var_lats, lons: var_lons);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<ColorScaleStop> sse_decode_list_color_scale_stop(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ColorScaleStop>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_color_scale_stop(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StormTrack> sse_decode_list_storm_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StormTrack>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_storm_track(deserializer));
    }
    return ans_;
  }

  @protected
  List<TrackPoint> sse_decode_list_track_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrackPoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track_point(deserializer));
    }
    return ans_;
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RadarFrame sse_decode_radar_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_productCode = sse_decode_i_32(deserializer);
    var var_productName = sse_decode_String(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_siteLat = sse_decode_f_64(deserializer);
    var var_siteLon = sse_decode_f_64(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_elevationDeg = sse_decode_f_32(deserializer);
    var var_vcp = sse_decode_i_32(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_png = sse_decode_list_prim_u_8_strict(deserializer);
    var var_north = sse_decode_f_64(deserializer);
    var var_south = sse_decode_f_64(deserializer);
    var var_east = sse_decode_f_64(deserializer);
    var var_west = sse_decode_f_64(deserializer);
    return RadarFrame(
      productCode: var_productCode,
      productName: var_productName,
      unit: var_unit,
      siteLat: var_siteLat,
      siteLon: var_siteLon,
      timestamp: var_timestamp,
      elevationDeg: var_elevationDeg,
      vcp: var_vcp,
      width: var_width,
      height: var_height,
      png: var_png,
      north: var_north,
      south: var_south,
      east: var_east,
      west: var_west,
    );
  }

  @protected
  RawFrame sse_decode_raw_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return RawFrame(width: var_width, height: var_height, rgba: var_rgba);
  }

  @protected
  SampleResult sse_decode_sample_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_rangeFolded = sse_decode_bool(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_distanceKm = sse_decode_f_64(deserializer);
    var var_beamHeightM = sse_decode_f_64(deserializer);
    var var_azimuthDeg = sse_decode_f_64(deserializer);
    var var_elevationDeg = sse_decode_f_32(deserializer);
    return SampleResult(
      value: var_value,
      rangeFolded: var_rangeFolded,
      unit: var_unit,
      distanceKm: var_distanceKm,
      beamHeightM: var_beamHeightM,
      azimuthDeg: var_azimuthDeg,
      elevationDeg: var_elevationDeg,
    );
  }

  @protected
  StormTrack sse_decode_storm_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_lat = sse_decode_f_64(deserializer);
    var var_lon = sse_decode_f_64(deserializer);
    var var_tracked = sse_decode_bool(deserializer);
    var var_speedKt = sse_decode_f_32(deserializer);
    var var_headingDeg = sse_decode_f_32(deserializer);
    var var_forecast = sse_decode_list_track_point(deserializer);
    var var_errorNm = sse_decode_f_32(deserializer);
    return StormTrack(
      id: var_id,
      lat: var_lat,
      lon: var_lon,
      tracked: var_tracked,
      speedKt: var_speedKt,
      headingDeg: var_headingDeg,
      forecast: var_forecast,
      errorNm: var_errorNm,
    );
  }

  @protected
  TrackPoint sse_decode_track_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_minutes = sse_decode_f_32(deserializer);
    var var_lat = sse_decode_f_64(deserializer);
    var var_lon = sse_decode_f_64(deserializer);
    return TrackPoint(minutes: var_minutes, lat: var_lat, lon: var_lon);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  Volume3DFrame sse_decode_volume_3_d_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_png = sse_decode_list_prim_u_8_strict(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    return Volume3DFrame(
      width: var_width,
      height: var_height,
      png: var_png,
      timestamp: var_timestamp,
    );
  }

  @protected
  Volume3DInfo sse_decode_volume_3_d_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gpu = sse_decode_bool(deserializer);
    var var_halfExtentM = sse_decode_f_32(deserializer);
    var var_topM = sse_decode_f_32(deserializer);
    return Volume3DInfo(
      gpu: var_gpu,
      halfExtentM: var_halfExtentM,
      topM: var_topM,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_color_scale(ColorScale self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_color_scale_stop(self.stops, serializer);
    sse_encode_bool(self.interpolate, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_u_8(self.rfR, serializer);
    sse_encode_u_8(self.rfG, serializer);
    sse_encode_u_8(self.rfB, serializer);
  }

  @protected
  void sse_encode_color_scale_stop(
    ColorScaleStop self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.value, serializer);
    sse_encode_u_8(self.r, serializer);
    sse_encode_u_8(self.g, serializer);
    sse_encode_u_8(self.b, serializer);
    sse_encode_u_8(self.a, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_glm_result(GlmResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_list_prim_f_32_strict(self.lats, serializer);
    sse_encode_list_prim_f_32_strict(self.lons, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_color_scale_stop(
    List<ColorScaleStop> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_color_scale_stop(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_storm_track(
    List<StormTrack> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_storm_track(item, serializer);
    }
  }

  @protected
  void sse_encode_list_track_point(
    List<TrackPoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track_point(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_radar_frame(RadarFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.productCode, serializer);
    sse_encode_String(self.productName, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_f_64(self.siteLat, serializer);
    sse_encode_f_64(self.siteLon, serializer);
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_f_32(self.elevationDeg, serializer);
    sse_encode_i_32(self.vcp, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.png, serializer);
    sse_encode_f_64(self.north, serializer);
    sse_encode_f_64(self.south, serializer);
    sse_encode_f_64(self.east, serializer);
    sse_encode_f_64(self.west, serializer);
  }

  @protected
  void sse_encode_raw_frame(RawFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }

  @protected
  void sse_encode_sample_result(SampleResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_f_32(self.value, serializer);
    sse_encode_bool(self.rangeFolded, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_f_64(self.distanceKm, serializer);
    sse_encode_f_64(self.beamHeightM, serializer);
    sse_encode_f_64(self.azimuthDeg, serializer);
    sse_encode_f_32(self.elevationDeg, serializer);
  }

  @protected
  void sse_encode_storm_track(StormTrack self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_f_64(self.lat, serializer);
    sse_encode_f_64(self.lon, serializer);
    sse_encode_bool(self.tracked, serializer);
    sse_encode_f_32(self.speedKt, serializer);
    sse_encode_f_32(self.headingDeg, serializer);
    sse_encode_list_track_point(self.forecast, serializer);
    sse_encode_f_32(self.errorNm, serializer);
  }

  @protected
  void sse_encode_track_point(TrackPoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.minutes, serializer);
    sse_encode_f_64(self.lat, serializer);
    sse_encode_f_64(self.lon, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_volume_3_d_frame(
    Volume3DFrame self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.png, serializer);
    sse_encode_i_64(self.timestamp, serializer);
  }

  @protected
  void sse_encode_volume_3_d_info(Volume3DInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.gpu, serializer);
    sse_encode_f_32(self.halfExtentM, serializer);
    sse_encode_f_32(self.topM, serializer);
  }
}
