// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_sample`, `convert`

/// Decode a full Level 2 (Archive II) volume and render one moment at one
/// elevation cut. `moment`: REF, VEL, SW, ZDR, PHI, or RHO.
Future<RadarFrame> renderLevel2Frame({
  required List<int> data,
  required String moment,
  required int elevationIndex,
  required int imageSize,
}) => RustLib.instance.api.crateApiRadarRenderLevel2Frame(
  data: data,
  moment: moment,
  elevationIndex: elevationIndex,
  imageSize: imageSize,
);

/// Elevation angles (deg) available for a moment in a Level 2 volume.
Future<Float32List> level2Cuts({
  required List<int> data,
  required String moment,
}) => RustLib.instance.api.crateApiRadarLevel2Cuts(data: data, moment: moment);

/// Viewport-matched render of a Level 3 product (sharp at any zoom).
Future<RadarFrame> renderLevel3View({
  required List<int> data,
  required double north,
  required double south,
  required double east,
  required double west,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRadarRenderLevel3View(
  data: data,
  north: north,
  south: south,
  east: east,
  west: west,
  width: width,
  height: height,
);

/// Viewport-matched render of a Level 2 moment/cut (sharp at any zoom).
Future<RadarFrame> renderLevel2View({
  required List<int> data,
  required String moment,
  required int elevationIndex,
  required double north,
  required double south,
  required double east,
  required double west,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRadarRenderLevel2View(
  data: data,
  moment: moment,
  elevationIndex: elevationIndex,
  north: north,
  south: south,
  east: east,
  west: west,
  width: width,
  height: height,
);

/// Parse a GOES GLM L2 LCFA netCDF file (pure-Rust HDF5 subset reader).
Future<GlmResult> parseGlm({required List<int> data}) =>
    RustLib.instance.api.crateApiRadarParseGlm(data: data);

/// Sample a Level 3 product file at a geographic point.
Future<SampleResult> sampleLevel3({
  required List<int> data,
  required double lat,
  required double lon,
}) => RustLib.instance.api.crateApiRadarSampleLevel3(
  data: data,
  lat: lat,
  lon: lon,
);

/// Sample a Level 2 volume's moment/cut at a geographic point.
Future<SampleResult> sampleLevel2({
  required List<int> data,
  required String moment,
  required int elevationIndex,
  required double lat,
  required double lon,
}) => RustLib.instance.api.crateApiRadarSampleLevel2(
  data: data,
  moment: moment,
  elevationIndex: elevationIndex,
  lat: lat,
  lon: lon,
);

/// Decode a raw Level 3 product file and render it to a georeferenced RGBA
/// PNG image, ready to overlay on the map.
Future<RadarFrame> renderLevel3Frame({
  required List<int> data,
  required int imageSize,
}) => RustLib.instance.api.crateApiRadarRenderLevel3Frame(
  data: data,
  imageSize: imageSize,
);

/// Render a 3D volume view of a Level 2 volume's reflectivity as a PNG.
Future<Volume3DFrame> renderVolume3D({
  required List<int> data,
  required double yawDeg,
  required double pitchDeg,
  required double zoom,
  required double dbzMin,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRadarRenderVolume3D(
  data: data,
  yawDeg: yawDeg,
  pitchDeg: pitchDeg,
  zoom: zoom,
  dbzMin: dbzMin,
  width: width,
  height: height,
);

/// Build (or rebuild) the 3D session for one volume + moment
/// (REF, SRM, VEL, ZDR, RHO, HCA).
///
/// `hidden_classes` is for HCA only, and is passed here rather than set after
/// opening so switching back to it cannot flash a frame with the
/// switched-off classes drawn.
Future<Volume3DInfo> volume3DOpen({
  required List<int> data,
  required String moment,
  required double threshold,
  required List<int> hiddenClasses,
}) => RustLib.instance.api.crateApiRadarVolume3DOpen(
  data: data,
  moment: moment,
  threshold: threshold,
  hiddenClasses: hiddenClasses,
);

/// Update the 3D opacity threshold without rebuilding the grid.
Future<void> volume3DSetThreshold({required double threshold}) => RustLib
    .instance
    .api
    .crateApiRadarVolume3DSetThreshold(threshold: threshold);

/// Show or hide individual hydrometeor classes, by class id. Repaints the
/// palette; the grid is not rebuilt.
Future<void> volume3DSetHiddenClasses({required List<int> classes}) => RustLib
    .instance
    .api
    .crateApiRadarVolume3DSetHiddenClasses(classes: classes);

/// Render one free-fly frame. `clip` = [minx,miny,minz,maxx,maxy,maxz] 0..1.
Future<RawFrame> volume3DRenderFly({
  required double eyeX,
  required double eyeY,
  required double eyeZ,
  required double yawDeg,
  required double pitchDeg,
  required List<double> clip,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRadarVolume3DRenderFly(
  eyeX: eyeX,
  eyeY: eyeY,
  eyeZ: eyeZ,
  yawDeg: yawDeg,
  pitchDeg: pitchDeg,
  clip: clip,
  width: width,
  height: height,
);

/// Decode an MRMS national mosaic (gzipped GRIB2) and render a view box.
Future<RadarFrame> renderMrmsView({
  required List<int> data,
  required double north,
  required double south,
  required double east,
  required double west,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRadarRenderMrmsView(
  data: data,
  north: north,
  south: south,
  east: east,
  west: west,
  width: width,
  height: height,
);

/// Drape a basemap image (RGBA8, north-up, covering the volume extent) on
/// the 3D ground plane.
Future<void> volume3DSetGround({
  required List<int> rgba,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRadarVolume3DSetGround(
  rgba: rgba,
  width: width,
  height: height,
);

/// Ground-plane bounds of the open 3D session: [north, south, east, west].
Future<Float64List> volume3DGroundBounds() =>
    RustLib.instance.api.crateApiRadarVolume3DGroundBounds();

/// On-device future radar: estimate motion between two consecutive frames
/// and extrapolate. `source` is "L3" or "MRMS".
Future<RadarFrame> nowcastView({
  required List<int> prev,
  required List<int> latest,
  required String source,
  required double minutes,
  required double north,
  required double south,
  required double east,
  required double west,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRadarNowcastView(
  prev: prev,
  latest: latest,
  source: source,
  minutes: minutes,
  north: north,
  south: south,
  east: east,
  west: west,
  width: width,
  height: height,
);

/// Read storm tracks out of a Level 3 STI product (code 58, key `xxx_NST_`).
Future<List<StormTrack>> stormTracks({required List<int> data}) =>
    RustLib.instance.api.crateApiRadarStormTracks(data: data);

/// Read mesocyclone detections from a Level 3 MD product (key `xxx_NMD_`).
/// An empty list means nothing was detected, not an error.
Future<List<MesoHit>> mesocyclones({required List<int> data}) =>
    RustLib.instance.api.crateApiRadarMesocyclones(data: data);

/// Import a `.pal` color table. Returns the product family it
/// applies to.
Future<String> installPalette({required String text}) =>
    RustLib.instance.api.crateApiRadarInstallPalette(text: text);

/// Drop imported palettes and return to the built-in ones.
Future<void> resetPalettes() =>
    RustLib.instance.api.crateApiRadarResetPalettes();

/// Open a Level 3 product file for repeated cursor sampling. The returned
/// handle names this session; sessions are per-caller, so two panes with a
/// cursor up do not read each other's data.
Future<int> inspectOpenLevel3({required List<int> data}) =>
    RustLib.instance.api.crateApiRadarInspectOpenLevel3(data: data);

/// Open a Level 2 moment/cut for repeated cursor sampling. Returns the
/// session handle.
Future<int> inspectOpenLevel2({
  required List<int> data,
  required String moment,
  required int elevationIndex,
}) => RustLib.instance.api.crateApiRadarInspectOpenLevel2(
  data: data,
  moment: moment,
  elevationIndex: elevationIndex,
);

/// Sample an open inspect session at a point (fast; no re-decode).
Future<SampleResult> inspectSample({
  required int session,
  required double lat,
  required double lon,
}) => RustLib.instance.api.crateApiRadarInspectSample(
  session: session,
  lat: lat,
  lon: lon,
);

/// Radar site of an open inspect session: [lat, lon].
Future<Float64List> inspectSite({required int session}) =>
    RustLib.instance.api.crateApiRadarInspectSite(session: session);

/// Close a session and free its sweep. Closing an unknown handle does
/// nothing, so a pane can close on its way out without ordering care.
Future<void> inspectClose({required int session}) =>
    RustLib.instance.api.crateApiRadarInspectClose(session: session);

/// The color scale a product is drawn with, so the key matches the map.
///
/// Pass `moment` for Level 2 and derived products, or leave it empty and pass
/// the Level 3 `product_code` from the rendered frame.
Future<ColorScale> colorScale({
  required int productCode,
  required String moment,
}) => RustLib.instance.api.crateApiRadarColorScale(
  productCode: productCode,
  moment: moment,
);

/// Give the 3D ground relief. `heights` is metres above sea level on a
/// north-up grid covering the same extent as the basemap, row-major from the
/// north edge. Pass an empty list to go back to a flat plane.
Future<void> volume3DSetTerrain({
  required List<double> heights,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRadarVolume3DSetTerrain(
  heights: heights,
  width: width,
  height: height,
);

/// Draw the cone of silence — the unsampled column above the radar's top cut
/// — as a translucent haze, so you can see what the radar cannot.
Future<void> volume3DShowCone({required bool show_}) =>
    RustLib.instance.api.crateApiRadarVolume3DShowCone(show_: show_);

/// Everything the UI needs to draw a key for what the colors mean.
class ColorScale {
  /// Breakpoints in ascending value order.
  final List<ColorScaleStop> stops;

  /// True when the renderer blends between stops, false when it steps. The
  /// key must be drawn the same way or it will not match the map.
  final bool interpolate;
  final String unit;

  /// Purple by convention, for bins that are range folded.
  final int rfR;
  final int rfG;
  final int rfB;

  const ColorScale({
    required this.stops,
    required this.interpolate,
    required this.unit,
    required this.rfR,
    required this.rfG,
    required this.rfB,
  });

  @override
  int get hashCode =>
      stops.hashCode ^
      interpolate.hashCode ^
      unit.hashCode ^
      rfR.hashCode ^
      rfG.hashCode ^
      rfB.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorScale &&
          runtimeType == other.runtimeType &&
          stops == other.stops &&
          interpolate == other.interpolate &&
          unit == other.unit &&
          rfR == other.rfR &&
          rfG == other.rfG &&
          rfB == other.rfB;
}

/// One breakpoint of a product's color scale.
class ColorScaleStop {
  final double value;
  final int r;
  final int g;
  final int b;
  final int a;

  const ColorScaleStop({
    required this.value,
    required this.r,
    required this.g,
    required this.b,
    required this.a,
  });

  @override
  int get hashCode =>
      value.hashCode ^ r.hashCode ^ g.hashCode ^ b.hashCode ^ a.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorScaleStop &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          r == other.r &&
          g == other.g &&
          b == other.b &&
          a == other.a;
}

/// Lightning flashes parsed from one GOES GLM L2 LCFA file.
class GlmResult {
  final PlatformInt64 timestamp;
  final Float32List lats;
  final Float32List lons;

  const GlmResult({
    required this.timestamp,
    required this.lats,
    required this.lons,
  });

  @override
  int get hashCode => timestamp.hashCode ^ lats.hashCode ^ lons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlmResult &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          lats == other.lats &&
          lons == other.lons;
}

/// One mesocyclone as the NWS's algorithm reports it.
class MesoHit {
  final String id;
  final double lat;
  final double lon;

  /// Strength rank as printed; the NWS treats 5 and above as significant.
  final String rank;

  /// The storm cell this belongs to, matching the storm track ids.
  final String stormId;
  final double maxRvKt;

  /// The tornado vortex signature algorithm fired on this circulation.
  final bool tvs;

  /// Mesocyclone Strength Index, -1 when absent.
  final int msi;

  /// Motion as the product prints it, e.g. "025/8" — see the engine for why
  /// this is not an angle.
  final String motion;

  const MesoHit({
    required this.id,
    required this.lat,
    required this.lon,
    required this.rank,
    required this.stormId,
    required this.maxRvKt,
    required this.tvs,
    required this.msi,
    required this.motion,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      lat.hashCode ^
      lon.hashCode ^
      rank.hashCode ^
      stormId.hashCode ^
      maxRvKt.hashCode ^
      tvs.hashCode ^
      msi.hashCode ^
      motion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MesoHit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          lat == other.lat &&
          lon == other.lon &&
          rank == other.rank &&
          stormId == other.stormId &&
          maxRvKt == other.maxRvKt &&
          tvs == other.tvs &&
          msi == other.msi &&
          motion == other.motion;
}

/// A ready-to-display radar frame: RGBA pixels plus the geographic bounds the
/// map should stretch them across, and metadata for the UI.
class RadarFrame {
  final int productCode;
  final String productName;
  final String unit;
  final double siteLat;
  final double siteLon;

  /// Unix seconds of the source volume scan.
  final PlatformInt64 timestamp;
  final double elevationDeg;
  final int vcp;
  final int width;
  final int height;
  final Uint8List png;
  final double north;
  final double south;
  final double east;
  final double west;

  const RadarFrame({
    required this.productCode,
    required this.productName,
    required this.unit,
    required this.siteLat,
    required this.siteLon,
    required this.timestamp,
    required this.elevationDeg,
    required this.vcp,
    required this.width,
    required this.height,
    required this.png,
    required this.north,
    required this.south,
    required this.east,
    required this.west,
  });

  @override
  int get hashCode =>
      productCode.hashCode ^
      productName.hashCode ^
      unit.hashCode ^
      siteLat.hashCode ^
      siteLon.hashCode ^
      timestamp.hashCode ^
      elevationDeg.hashCode ^
      vcp.hashCode ^
      width.hashCode ^
      height.hashCode ^
      png.hashCode ^
      north.hashCode ^
      south.hashCode ^
      east.hashCode ^
      west.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RadarFrame &&
          runtimeType == other.runtimeType &&
          productCode == other.productCode &&
          productName == other.productName &&
          unit == other.unit &&
          siteLat == other.siteLat &&
          siteLon == other.siteLon &&
          timestamp == other.timestamp &&
          elevationDeg == other.elevationDeg &&
          vcp == other.vcp &&
          width == other.width &&
          height == other.height &&
          png == other.png &&
          north == other.north &&
          south == other.south &&
          east == other.east &&
          west == other.west;
}

/// A raw RGBA frame (no PNG encode) for fast display.
class RawFrame {
  final int width;
  final int height;
  final Uint8List rgba;

  const RawFrame({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

/// Result of sampling a product at a point (the "inspector" tool).
class SampleResult {
  final double? value;
  final bool rangeFolded;
  final String unit;
  final double distanceKm;
  final double beamHeightM;

  /// Compass bearing from the radar to the sampled point.
  final double azimuthDeg;

  /// Elevation angle of the sampled sweep.
  final double elevationDeg;

  const SampleResult({
    this.value,
    required this.rangeFolded,
    required this.unit,
    required this.distanceKm,
    required this.beamHeightM,
    required this.azimuthDeg,
    required this.elevationDeg,
  });

  @override
  int get hashCode =>
      value.hashCode ^
      rangeFolded.hashCode ^
      unit.hashCode ^
      distanceKm.hashCode ^
      beamHeightM.hashCode ^
      azimuthDeg.hashCode ^
      elevationDeg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SampleResult &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          rangeFolded == other.rangeFolded &&
          unit == other.unit &&
          distanceKm == other.distanceKm &&
          beamHeightM == other.beamHeightM &&
          azimuthDeg == other.azimuthDeg &&
          elevationDeg == other.elevationDeg;
}

/// A storm cell as the NWS's own SCIT reports it.
class StormTrack {
  /// NWS cell id, e.g. "O8" — stable between volumes.
  final String id;
  final double lat;
  final double lon;

  /// False when the cell has no movement solution yet.
  final bool tracked;
  final double speedKt;

  /// Degrees true the storm is heading toward.
  final double headingDeg;
  final List<TrackPoint> forecast;

  /// NWS forecast track error in nautical miles, where given.
  final double errorNm;

  const StormTrack({
    required this.id,
    required this.lat,
    required this.lon,
    required this.tracked,
    required this.speedKt,
    required this.headingDeg,
    required this.forecast,
    required this.errorNm,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      lat.hashCode ^
      lon.hashCode ^
      tracked.hashCode ^
      speedKt.hashCode ^
      headingDeg.hashCode ^
      forecast.hashCode ^
      errorNm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StormTrack &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          lat == other.lat &&
          lon == other.lon &&
          tracked == other.tracked &&
          speedKt == other.speedKt &&
          headingDeg == other.headingDeg &&
          forecast == other.forecast &&
          errorNm == other.errorNm;
}

/// One projected position along a storm's forecast path.
class TrackPoint {
  final double minutes;
  final double lat;
  final double lon;

  const TrackPoint({
    required this.minutes,
    required this.lat,
    required this.lon,
  });

  @override
  int get hashCode => minutes.hashCode ^ lat.hashCode ^ lon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackPoint &&
          runtimeType == other.runtimeType &&
          minutes == other.minutes &&
          lat == other.lat &&
          lon == other.lon;
}

/// A rendered 3D volume frame.
class Volume3DFrame {
  final int width;
  final int height;
  final Uint8List png;
  final PlatformInt64 timestamp;

  const Volume3DFrame({
    required this.width,
    required this.height,
    required this.png,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ png.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Volume3DFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          png == other.png &&
          timestamp == other.timestamp;
}

/// Info about an open 3D fly-through session.
class Volume3DInfo {
  final bool gpu;
  final double halfExtentM;
  final double topM;

  const Volume3DInfo({
    required this.gpu,
    required this.halfExtentM,
    required this.topM,
  });

  @override
  int get hashCode => gpu.hashCode ^ halfExtentM.hashCode ^ topM.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Volume3DInfo &&
          runtimeType == other.runtimeType &&
          gpu == other.gpu &&
          halfExtentM == other.halfExtentM &&
          topM == other.topM;
}
