// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_sample`, `convert`

/// Decode a full Level 2 (Archive II) volume and render one moment at one
/// elevation cut. `moment`: REF, VEL, SW, ZDR, PHI, or RHO.
Future<RadarFrame> renderLevel2Frame({
  required List<int> data,
  required String moment,
  required int elevationIndex,
  required int imageSize,
}) => RustLib.instance.api.crateApiRadarRenderLevel2Frame(
  data: data,
  moment: moment,
  elevationIndex: elevationIndex,
  imageSize: imageSize,
);

/// Elevation angles (deg) available for a moment in a Level 2 volume.
Future<Float32List> level2Cuts({
  required List<int> data,
  required String moment,
}) => RustLib.instance.api.crateApiRadarLevel2Cuts(data: data, moment: moment);

/// Viewport-matched render of a Level 3 product (sharp at any zoom).
Future<RadarFrame> renderLevel3View({
  required List<int> data,
  required double north,
  required double south,
  required double east,
  required double west,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRadarRenderLevel3View(
  data: data,
  north: north,
  south: south,
  east: east,
  west: west,
  width: width,
  height: height,
);

/// Viewport-matched render of a Level 2 moment/cut (sharp at any zoom).
Future<RadarFrame> renderLevel2View({
  required List<int> data,
  required String moment,
  required int elevationIndex,
  required double north,
  required double south,
  required double east,
  required double west,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRadarRenderLevel2View(
  data: data,
  moment: moment,
  elevationIndex: elevationIndex,
  north: north,
  south: south,
  east: east,
  west: west,
  width: width,
  height: height,
);

/// Sample a Level 3 product file at a geographic point.
Future<SampleResult> sampleLevel3({
  required List<int> data,
  required double lat,
  required double lon,
}) => RustLib.instance.api.crateApiRadarSampleLevel3(
  data: data,
  lat: lat,
  lon: lon,
);

/// Sample a Level 2 volume's moment/cut at a geographic point.
Future<SampleResult> sampleLevel2({
  required List<int> data,
  required String moment,
  required int elevationIndex,
  required double lat,
  required double lon,
}) => RustLib.instance.api.crateApiRadarSampleLevel2(
  data: data,
  moment: moment,
  elevationIndex: elevationIndex,
  lat: lat,
  lon: lon,
);

/// Decode a raw Level 3 product file and render it to a georeferenced RGBA
/// PNG image, ready to overlay on the map.
Future<RadarFrame> renderLevel3Frame({
  required List<int> data,
  required int imageSize,
}) => RustLib.instance.api.crateApiRadarRenderLevel3Frame(
  data: data,
  imageSize: imageSize,
);

/// A ready-to-display radar frame: RGBA pixels plus the geographic bounds the
/// map should stretch them across, and metadata for the UI.
class RadarFrame {
  final int productCode;
  final String productName;
  final String unit;
  final double siteLat;
  final double siteLon;

  /// Unix seconds of the source volume scan.
  final PlatformInt64 timestamp;
  final double elevationDeg;
  final int vcp;
  final int width;
  final int height;
  final Uint8List png;
  final double north;
  final double south;
  final double east;
  final double west;

  const RadarFrame({
    required this.productCode,
    required this.productName,
    required this.unit,
    required this.siteLat,
    required this.siteLon,
    required this.timestamp,
    required this.elevationDeg,
    required this.vcp,
    required this.width,
    required this.height,
    required this.png,
    required this.north,
    required this.south,
    required this.east,
    required this.west,
  });

  @override
  int get hashCode =>
      productCode.hashCode ^
      productName.hashCode ^
      unit.hashCode ^
      siteLat.hashCode ^
      siteLon.hashCode ^
      timestamp.hashCode ^
      elevationDeg.hashCode ^
      vcp.hashCode ^
      width.hashCode ^
      height.hashCode ^
      png.hashCode ^
      north.hashCode ^
      south.hashCode ^
      east.hashCode ^
      west.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RadarFrame &&
          runtimeType == other.runtimeType &&
          productCode == other.productCode &&
          productName == other.productName &&
          unit == other.unit &&
          siteLat == other.siteLat &&
          siteLon == other.siteLon &&
          timestamp == other.timestamp &&
          elevationDeg == other.elevationDeg &&
          vcp == other.vcp &&
          width == other.width &&
          height == other.height &&
          png == other.png &&
          north == other.north &&
          south == other.south &&
          east == other.east &&
          west == other.west;
}

/// Result of sampling a product at a point (the "inspector" tool).
class SampleResult {
  final double? value;
  final bool rangeFolded;
  final String unit;
  final double distanceKm;
  final double beamHeightM;

  const SampleResult({
    this.value,
    required this.rangeFolded,
    required this.unit,
    required this.distanceKm,
    required this.beamHeightM,
  });

  @override
  int get hashCode =>
      value.hashCode ^
      rangeFolded.hashCode ^
      unit.hashCode ^
      distanceKm.hashCode ^
      beamHeightM.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SampleResult &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          rangeFolded == other.rangeFolded &&
          unit == other.unit &&
          distanceKm == other.distanceKm &&
          beamHeightM == other.beamHeightM;
}
