// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert`

/// Decode a full Level 2 (Archive II) volume and render one moment at one
/// elevation cut. `moment`: REF, VEL, SW, ZDR, PHI, or RHO.
Future<RadarFrame> renderLevel2Frame({
  required List<int> data,
  required String moment,
  required int elevationIndex,
  required int imageSize,
}) => RustLib.instance.api.crateApiRadarRenderLevel2Frame(
  data: data,
  moment: moment,
  elevationIndex: elevationIndex,
  imageSize: imageSize,
);

/// Elevation angles (deg) available for a moment in a Level 2 volume.
Future<Float32List> level2Cuts({
  required List<int> data,
  required String moment,
}) => RustLib.instance.api.crateApiRadarLevel2Cuts(data: data, moment: moment);

/// Decode a raw Level 3 product file and render it to a georeferenced RGBA
/// PNG image, ready to overlay on the map.
Future<RadarFrame> renderLevel3Frame({
  required List<int> data,
  required int imageSize,
}) => RustLib.instance.api.crateApiRadarRenderLevel3Frame(
  data: data,
  imageSize: imageSize,
);

/// A ready-to-display radar frame: RGBA pixels plus the geographic bounds the
/// map should stretch them across, and metadata for the UI.
class RadarFrame {
  final int productCode;
  final String productName;
  final String unit;
  final double siteLat;
  final double siteLon;

  /// Unix seconds of the source volume scan.
  final PlatformInt64 timestamp;
  final double elevationDeg;
  final int vcp;
  final int width;
  final int height;
  final Uint8List png;
  final double north;
  final double south;
  final double east;
  final double west;

  const RadarFrame({
    required this.productCode,
    required this.productName,
    required this.unit,
    required this.siteLat,
    required this.siteLon,
    required this.timestamp,
    required this.elevationDeg,
    required this.vcp,
    required this.width,
    required this.height,
    required this.png,
    required this.north,
    required this.south,
    required this.east,
    required this.west,
  });

  @override
  int get hashCode =>
      productCode.hashCode ^
      productName.hashCode ^
      unit.hashCode ^
      siteLat.hashCode ^
      siteLon.hashCode ^
      timestamp.hashCode ^
      elevationDeg.hashCode ^
      vcp.hashCode ^
      width.hashCode ^
      height.hashCode ^
      png.hashCode ^
      north.hashCode ^
      south.hashCode ^
      east.hashCode ^
      west.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RadarFrame &&
          runtimeType == other.runtimeType &&
          productCode == other.productCode &&
          productName == other.productName &&
          unit == other.unit &&
          siteLat == other.siteLat &&
          siteLon == other.siteLon &&
          timestamp == other.timestamp &&
          elevationDeg == other.elevationDeg &&
          vcp == other.vcp &&
          width == other.width &&
          height == other.height &&
          png == other.png &&
          north == other.north &&
          south == other.south &&
          east == other.east &&
          west == other.west;
}
