#!/usr/bin/env python3
"""Generate app/lib/data/nexrad_sites.g.dart from NCEI nexrad-stations.txt.

Fetch the source file with:
  curl -o tools/nexrad-stations.txt https://www.ncei.noaa.gov/access/homr/file/nexrad-stations.txt
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "nexrad-stations.txt"
OUT = ROOT / "app" / "lib" / "data" / "nexrad_sites.g.dart"


def main():
    lines = SRC.read_text().splitlines()
    header, ruler = lines[0], lines[1]

    # Column boundaries come from the dashed ruler line.
    spans = []
    start = None
    for i, ch in enumerate(ruler + " "):
        if ch == "-" and start is None:
            start = i
        elif ch != "-" and start is not None:
            spans.append((start, i))
            start = None

    def field(line, idx):
        s, e = spans[idx]
        return line[s:e].strip()

    names = [field(header, i) for i in range(len(spans))]
    col = {n: i for i, n in enumerate(names)}

    sites = []
    for line in lines[2:]:
        if not line.strip():
            continue
        icao = field(line, col["ICAO"])
        name = field(line, col["NAME"]).title()
        state = field(line, col["ST"])
        lat = float(field(line, col["LAT"]))
        lon = float(field(line, col["LON"]))
        elev = int(field(line, col["ELEV"]))
        stype = field(line, col["STNTYPE"])
        is_tdwr = "TDWR" in stype
        sites.append((icao, name, state, lat, lon, elev, is_tdwr))

    sites.sort()
    with OUT.open("w") as f:
        f.write("// GENERATED by tools/gen_sites.py — do not edit.\n")
        f.write("// Source: NCEI HOMR nexrad-stations.txt\n\n")
        f.write("class NexradSite {\n")
        f.write("  final String icao;\n")
        f.write("  final String name;\n")
        f.write("  final String state;\n")
        f.write("  final double lat;\n")
        f.write("  final double lon;\n")
        f.write("  final int elevFt;\n")
        f.write("  final bool isTdwr;\n\n")
        f.write("  const NexradSite(this.icao, this.name, this.state, this.lat,\n")
        f.write("      this.lon, this.elevFt, this.isTdwr);\n\n")
        f.write("  /// Site id used in AWS bucket keys (e.g. KTLX -> TLX).\n")
        f.write("  String get shortId => icao.length == 4 ? icao.substring(1) : icao;\n")
        f.write("}\n\n")
        f.write("const List<NexradSite> nexradSites = [\n")
        for icao, name, state, lat, lon, elev, tdwr in sites:
            f.write(
                f"  NexradSite('{icao}', '{name}', '{state}', {lat}, {lon}, {elev}, {str(tdwr).lower()}),\n"
            )
        f.write("];\n")
    print(f"wrote {OUT} with {len(sites)} sites")


if __name__ == "__main__":
    sys.exit(main())
